### ISSUE TITLE
Potential non consistency in documentation

### ISSUE THREAD

**Issue by denzor200** [boostorg/fusion#234]
https://www.boost.org/doc/libs/1_77_0/libs/fusion/doc/html/fusion/container/generation/functions/tiers.html
This documentation said that a const reference cannot be as an element of some tier.
However, this examples compiles successfully:
https://godbolt.org/z/9b3jh48xv

**Comment by djowel** [comment]
Your code is correct and allowed. The documentation is misleading and should be fixed.

**Comment by djowel** [comment]
Fixed in develop branch
